apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: cors-plugin
  annotations:
    kubernetes.io/ingress.class: kong
plugin: cors
config:
  origins:
    - "*"
  headers:
    - "*"
  exposed_headers:
    - "X-User-Sub"
    - "x-user-sub"
    - "X-User-Email"
    - "x-user-email"
  credentials: true
  max_age: 3600
  preflight_continue: true







