---
apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-cm
  labels:
    name: krakend-cm
data:
  krakend.json: |
    {
      "$schema": "https://www.krakend.io/schema/v2.8/krakend.json",
      "version": 3,
      "endpoints": [
        {
          "endpoint": "/api/lobby",
          "backend": [
            {
              "url_pattern": "/api/lobby",
              "host": [
                "lobby-svc"
              ]
            }
          ]
        }
      ],
      "extra_config": {
        "telemetry/logging": {
          "level": "DEBUG",
          "stdout": true,
          "syslog": false
        }
      }
    }