apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deployment
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        # Restarts the pod if the config changes
        checksum/config: {{ include (print $.Template.BasePath "/krakend-conf.yaml") . | sha256sum }}
      labels:
        app: krakend-pod
    spec:
      containers:
        - name: krakend
          image: devopsfaith/krakend:2.8.0
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          command: [ "/usr/bin/krakend" ]
          args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/krakend
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          env:
            - name: KRAKEND_PORT
              value: "8080"
      volumes:
        - name: config-volume
          configMap:
            name: krakend-cm