kong:
  # DB-less mode
  env:
    database: "off"
  # Prepare for k8s Ingress manifests...
  # The `Ingress` manifests in our applications
  # won't work without the Kong Ingress Controller
  ingressController:
    enabled: true
    ingressClass: kong

  proxy:
    type: ClusterIP
    http:
      enabled: true
      servicePort: 8080
    tls:
      enabled: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      path: /api
      hosts:
        - rso-2.janvasiljevic.com

