kong:
  env:
    database: "off"  # DB-less mode
    admin_gui_url: https://rso-2.janvasiljevic.com/api/kong

  ingressController:
    enabled: true
    ingressClass: kong  # Required for k8s Ingress manifests


  admin:
    enabled: true

  manager:
    enabled: true
    http:
      enabled: ture
    tls:
      enabled: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hostname: rso-2.janvasiljevic.com
      pathType: Prefix
      path: /api/kong

  proxy:
    type: ClusterIP
    http:
      enabled: true
    tls:
      enabled: false

    enabled: true

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"

      hostname: rso-2.janvasiljevic.com
      path: /api
      pathType: Prefix