db:
  name: "lobby"
  user: "lobby-user"
  password: "lobby-password"
  service: "lobby-db-service"

lobby:
  replicaCount: 1
  internalPort: 8080

image:
  name: "ghcr.io/rso-iota/rso-lobby"
  tag: "latest"



dns: rso-2.janvasiljevic.com