apiVersion: v1
kind: PersistentVolume
metadata:
  name: stats-redis-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stats-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-redis-deployment
spec:
  selector:
    matchLabels:
      app: stats-redis
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stats-redis
    spec:
      containers:
        - name: stats-redis-container
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-storage
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: stats-redis-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: stats-redis-svc
spec:
  selector:
    app: stats-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379