apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stats-app
  name: stats-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: stats-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: stats-app
    spec:
      containers:
        - image: {{ .Values.image.name}}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: stats-app
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 128Mi
          env:
            - name: NATS_URL
              value: "{{ .Values.env.NATS_URL }}"
            - name: LOG_JSON
              value: "{{ .Values.env.LOG_JSON }}"
            - name: REDIS_URL
              value: "{{ .Values.env.REDIS_URL }}"
            - name: GRAPHQL_PORT
              value: "{{ .Values.env.GRAPHQL_PORT }}"
          ports:
            - containerPort: {{ .Values.env.GRAPHQL_PORT }}