image:
  name: "ghcr.io/rso-iota/rso-game"
  tag: "latest"

game:
  replicaCount: 3

env:
  GAME_NATS_URL: "nats://nats.nats:4222"
  GAME_AUTH_EP: "http://auth-svc/api/auth/auth/user"
  GAME_REQUIRE_AUTH: "true"
  GAME_HTTP_PORT: 8080
  GAME_GRPC_PORT: 8081
  GAME_NUM_TEST_GAMES: 4
  GAME_TEST_SERVER: "true"
  GAME_LOG_JSON: "true"

dns: rso-2.janvasiljevic.com