image:
  name: "ghcr.io/rso-iota/rso-game"
  tag: "latest"

game:
  replicaCount: 3

env:
  NATS_URL: "nats://nats.nats:4222"
  AUTH_EP: "http://auth-svc/api/auth/auth/user"
  REQUIRE_AUTH: True
  BOT_SERVICE_URL: "bots-svc:8081"
  MIN_PLAYERS: 2
  NUM_TEST_GAMES: 4
  TEST_SERVER: True
  LOG_JSON: True
  BACKUP_REDIS_URL: "game-backup-redis-svc:6379"
  EXTERNAL_HTTP_PORT: 8080
  INTERNAL_HTTP_PORT: 8081
  TERMINATE_MINUTES: 5

dns: rso-2.janvasiljevic.com
