apiVersion: v2
name: Chart
description: Metrics service Helm chart
type: application
version: 0.1.0

dependencies:
  - name: metrics-server
    version: 3.12.2
    repository: https://kubernetes-sigs.github.io/metrics-server/
