apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lobby-app
  name: lobby-app-deployment
spec:
  replicas: {{ .Values.lobby.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: lobby-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: lobby-app
    spec:
      containers:
        - image: {{ .Values.image.name}}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: lobby-app
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 128Mi
          env:
            - name: SERVER_TOMCAT_MAX_THREADS
              value: "20"
            - name: JAVA_OPTS
              value: "-Xms100m -Xmx256m -XX:+UseSerialGC -Xss512k -XX:MaxRAM=100m"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.config.contextPath }}
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{.Values.db.service}}:5432/{{ .Values.db.name }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.db.user }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.db.password }}
            - name: LOGGING_STRUCTURED_FORMAT_CONSOLE
              value: ecs
              {{- range $key, $value := .Values.env }}
            - name: SVC_{{ $key | upper }}
              value: {{ $value | quote }}
              {{- end }}
          ports:
            - containerPort: {{ .Values.lobby.internalPort }}
            - containerPort: {{ .Values.config.grpcPort }}
          livenessProbe:
            httpGet:
              path: {{.Values.config.contextPath }}/actuator/health/liveness
              port: {{ .Values.lobby.internalPort }}
          readinessProbe:
            httpGet:
              path: {{.Values.config.contextPath }}/actuator/health/readiness
              port: {{ .Values.lobby.internalPort }}

