apiVersion: v1
kind: Service
metadata:
  name: lobby-svc
  namespace: apps
spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: {{ .Values.lobby.internalPort }}
    - protocol: TCP
      name: grpc-internal
      port: {{ .Values.config.grpcPort }}
      targetPort: {{ .Values.config.grpcPort }}
  selector:
    app: lobby-app
  type: ClusterIP