---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lobby-ingress
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: {{ .Values.dns }}
      http:
        paths:
          - path: /api/lobby
            pathType: Prefix
            backend:
              service:
                name: lobby-svc
                port:
                  number: 80
