apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lobby-app
  name: lobby-app-deployment
spec:
  replicas: {{ .Values.lobby.replicaCount }}
  selector:
    matchLabels:
      app: lobby-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: lobby-app
    spec:
      containers:
        - image: {{ .Values.image.name}}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: lobby-app
          resources: { }
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{.Values.db.service}}:5432/{{ .Values.db.name }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.db.user }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.db.password }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.lobby.internalPort }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.lobby.internalPort }}

