apiVersion: v1
kind: Service
metadata:
  labels:
    app: lobby-service
  name: lobby-app-service
spec:
  ports:
    - name: 80-{{ .Values.lobby.internalPort }}
      port: 80
      protocol: TCP
      targetPort: {{ .Values.lobby.internalPort }}
  selector:
    app: lobby-app
  type: ClusterIP