---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lobby-ingress
  namespace: apps
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  rules:
    - host: {{ .Values.dns }}
      http:
        paths:
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: lobby-service
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.dns }}
