apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lobby-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby-postgres-deployment
spec:
  selector:
    matchLabels:
      app: lobby-postgres
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lobby-postgres
    spec:
      containers:
        - name: lobby-postgres-container
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.dbName }}
            - name: POSTGRES_USER
              value: {{ .Values.dbUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.dbPassword }}
              # set the path to the postgres data directory
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: lobby-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbServiceName }}
spec:
  selector:
    app: lobby-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432