apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso-frontend-deployment
  namespace: apps
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rso-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: rso-frontend
    spec:
      containers:
        - name: rso-front-container
          env:
            - name: VITE_BACKEND_API
              value: {{ .Values.env.backendApi }}
            - name: VITE_KC_AUTHORITY
              value: {{ .Values.env.keycloakAuthority }}
            - name: VITE_KC_CLIENT_ID
              value: {{ .Values.env.keycloakClientId }}
            - name: VITE_DISCORD_WEBHOOK
              value: {{ .Values.env.discordWebhook }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.appPort }}
