apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso-frontend-deployment
  namespace: apps
spec:
  selector:
    matchLabels:
      app: rso-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: rso-frontend
    spec:
      containers:
        - name: rso-front-container
          env:
            - name: VITE_BACKEND_API
              value: {{ .Values.env.backendApi }}
            - name: VITE_KC_AUTHORITY
              value: {{ .Values.env.keycloakClientId }}
            - name: VITE_KC_CLIENT_ID
              value: {{ .Values.env.keycloakClientId }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.appPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: rso-frontend-svc
  namespace: apps
spec:
  selector:
    app: rso-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.appPort }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rso-frontend-ingress
  namespace: apps
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  rules:
    - host: {{ .Values.dns }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rso-frontend-svc
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.dns }}
