apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rso-frontend-image-updater
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: api=ghcr.io/rso-iota/rso-fe
    argocd-image-updater.argoproj.io/update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://github.com/rso-iota/rso-services.git
    targetRevision: HEAD
    path: services/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
---
