apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: fe=ghcr.io/rso-iota/rso-fe:latest
    argocd-image-updater.argoproj.io/fe.update-strategy: digest
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: https://github.com/rso-iota/rso-services.git
    targetRevision: HEAD
    path: services/frontend

  destination:
    server: https://kubernetes.default.svc
    namespace: apps
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lobby-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: lobby=ghcr.io/rso-iota/rso-lobby:latest
    argocd-image-updater.argoproj.io/lobby.update-strategy: digest
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: https://github.com/rso-iota/rso-services.git
    targetRevision: HEAD
    path: services/lobby
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: game=ghcr.io/rso-iota/rso-game:latest
    argocd-image-updater.argoproj.io/game.update-strategy: digest
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: https://github.com/rso-iota/rso-services.git
    targetRevision: HEAD
    path: services/game
  destination:
    server: https://kubernetes.default.svc
    namespace: apps

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: game=ghcr.io/rso-iota/rso-game:latest
    argocd-image-updater.argoproj.io/game.update-strategy: digest
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: https://github.com/rso-iota/rso-services.git
    targetRevision: HEAD
    path: services/game
  destination:
    server: https://kubernetes.default.svc
    namespace: apps

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: auth=ghcr.io/rso-iota/rso-auth-users:latest
    argocd-image-updater.argoproj.io/auth.update-strategy: digest
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: https://github.com/rso-iota/rso-services.git
    targetRevision: HEAD
    path: services/auth-users
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rso-iota/rso-services.git
    targetRevision: HEAD
    path: services/kong
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stats-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: stats=ghcr.io/rso-iota/rso-stats:latest
    argocd-image-updater.argoproj.io/stats.update-strategy: digest
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: https://github.com/rso-iota/rso-services.git
    targetRevision: HEAD
    path: services/stats
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bots-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: bots=ghcr.io/rso-iota/rso-bots:latest
    argocd-image-updater.argoproj.io/bots.update-strategy: digest
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: https://github.com/rso-iota/rso-services.git
    targetRevision: HEAD
    path: services/bots
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: replay-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: replay=ghcr.io/rso-iota/rso-replay:latest
    argocd-image-updater.argoproj.io/replay.update-strategy: digest
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: https://github.com/rso-iota/rso-services.git
    targetRevision: HEAD
    path: services/replay
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
