---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
spec:
  forwardAuth:
    address: http://auth-svc:80{{ .Values.config.contextPath}}/auth
    trustForwardHeader: true

