apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: apps
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.auth.internalPort }}
  selector:
    app: auth-app
  type: ClusterIP