---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
spec:
  forwardAuth:
    address: http://{{.Values.svcName}}/{{ .Values.config.contextPath}}/auth
    trustForwardHeader: true

