apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: apps
spec:
  ports:
    - name: 80-{{ .Values.auth.internalPort }}
      port: 80
      protocol: TCP
      targetPort: {{ .Values.auth.internalPort }}
  selector:
    app: auth-app
  type: ClusterIP