---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: cors-plugin
spec:
  rules:
    - host: {{ .Values.dns }}
      http:
        paths:
          - path: {{ .Values.config.contextPath }}
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  number: 80