auth:
  replicaCount: 1
  internalPort: 8080

image:
  name: "ghcr.io/rso-iota/rso-auth-users"
  tag: "latest"

config:
  contextPath: "/api/auth"

env:
  # Most of these settings should be set in ArgoCD so they aren't pushed to the repo
  KEYCLOAK_AUTH_SERVER_URL: "https://rso-keycloak.janvasiljevic.com"
  KEYCLOAK_CLIENT_ID: "external-client"
  KEYCLOAK_REALM: "aga.rso"
  KEYCLOAK_ADMIN_SERVER_URL: "https://rso-keycloak.janvasiljevic.com"
  KEYCLOAK_ADMIN_CLIENT_ID: ""
  KEYCLOAK_ADMIN_REALM: ""
  KEYCLOAK_ADMIN_USERNAME: ""
  KEYCLOAK_ADMIN_PASSWORD: ""
  KEYCLOAK_ADMIN_FRONTEND_CLIENT_ID: "fe-client"
  KEYCLOAK_ADMIN_FRONTEND_REALM: "aga.rso"
  KEYCLOAK_FRONTEND_CLIENT_ID: "fe-client"
  AUTH_FORWARD_LOG_X_FORWARDED_HEADERS: "true"

dns: rso-2.janvasiljevic.com
svcName: auth-svc