apiVersion: v1
kind: Service
metadata:
  name: bots-svc
  namespace: apps
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.env.GRAPHQL_PORT }}
  selector:
    app: bots-app
  type: ClusterIP
