apiVersion: v1
kind: Service
metadata:
  name: bots-svc
  namespace: apps
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.env.GRPC_PORT }}
      targetPort: {{ .Values.env.GRPC_PORT }}
  selector:
    app: bots-app
  type: ClusterIP
