apiVersion: v1
kind: Service
metadata:
  name: bots-svc
  namespace: apps
spec:
  ports:
    - protocol: TCP
      port: grpc_port
      targetPort: grpc_port
  selector:
    app: bots-app
  type: ClusterIP
