traefik:
  logs:
    general:
      noColor: true
      level: DEBUG
    access:
      enabled: true

  ports:
    traefik:
      exposedPort: 8080

  ingressRoute:
    dashboard:
      enabled: true
      entryPoints:
        - web

dns: 'janvasiljevic.com'

#  resources:
#    requests:
#      cpu: 100m
#      memory: 32Mi
#    limits:
#      cpu: 1


