apiVersion: v1
kind: Service
metadata:
  name: replay-svc
  namespace: apps
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.env.UVICORN_PORT }}
      targetPort: {{ .Values.env.UVICORN_PORT }}
  selector:
    app: replay-app
  type: ClusterIP
