apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: replay-mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: replay-mongodb-deployment
spec:
  selector:
    matchLabels:
      app: replay-mongodb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: replay-mongodb
    spec:
      containers:
        - name: replay-mongodb-container
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
              # set the path to the mongodb data directory
            - name: MONGO_INITDB_DATA_PATH
              value: /data/db
            volumeMounts:
            - mountPath: /data/db
              name: mongodb-storage
          volumes:
          - name: mongodb-storage
            persistentVolumeClaim:
            claimName: replay-mongodb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: replay-mongodb-svc
spec:
  selector:
    app: replay-mongodb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
