apiVersion: apps/v1
kind: Deployment
metadata:
  name: replay-app-deployment
spec:
  replicas: {{ .Values.replay.replicaCount }}
  selector:
    matchLabels:
      app: replay-app
  template:
    metadata:
      labels:
        app: replay-app
    spec:
      containers:
      - name: replay-app
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        env:
        {{- range $key, $val := .Values.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.env.UVICORN_PORT }}
        livenessProbe:
          httpGet:
            path: /health/live
            port: {{ .Values.env.UVICORN_PORT }}
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: {{ .Values.env.UVICORN_PORT }}
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: frames-storage
          mountPath: /tmp/frames
      volumes:
      - name: frames-storage
        emptyDir: {}