apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rso-frontend-image-updater
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: api=ghcr.io/rso-iota/rso-fe
    argocd-image-updater.argoproj.io/update-strategy: digest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso-frontend-deployment
  namespace: apps
spec:
  selector:
    matchLabels:
      app: rso-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: rso-frontend
    spec:
      containers:
        - name: rso-front-container
          image: ghcr.io/rso-iota/rso-fe:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rso-frontend-svc
  namespace: apps
spec:
  selector:
    app: rso-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rso-frontend-ingress
  namespace: apps
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  rules:
    - host: rso.janvasiljevic.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rso-frontend-svc
                port:
                  number: 80
  tls:
    - secretName: rso-cert
      hosts:
        - rso.janvasiljevic.com
