apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: game-app
  name: game-app-statefulset
spec:
  replicas: {{ .Values.game.replicaCount }}
  serviceName: game-svc
  selector:
    matchLabels:
      app: game-app
  template:
    metadata:
      labels:
        app: game-app
    spec:
      containers:
        - image: {{ .Values.image.name}}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.env.GAME_HTTP_PORT }}
              name: httpws
            - containerPort:  {{ .Values.env.GAME_GRPC_PORT }}
              name: grpc
          imagePullPolicy: Always
          name: game-app
          resources:
            requests:
              memory: "20Mi"
          env:
            - name: GAME_NATS_URL
              value: {{ .Values.env.GAME_NATS_URL }}
            - name: GAME_AUTH_EP
              value: {{ .Values.env.GAME_AUTH_EP }}
            - name: GAME_REQUIRE_AUTH
              value: {{ .Values.env.GAME_REQUIRE_AUTH }}
            - name: GAME_HTTP_PORT
              value: {{ .Values.env.GAME_HTTP_PORT }}
            - name: GAME_GRPC_PORT
              value: {{ .Values.env.GAME_GRPC_PORT }}
            - name: GAME_NUM_TEST_GAMES
              value: {{ .Values.env.GAME_NUM_TEST_GAMES }}
            - name: GAME_TEST_SERVER
              value: {{ .Values.env.GAME_TEST_SERVER }}
            - name: GAME_LOG_JSON
              value: {{ .Values.env.GAME_LOG_JSON }}

