apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: websocket-headers
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    customRequestHeaders:
      Upgrade: "{http_upgrade}"
      Connection: "Upgrade"
      Host: "{host}"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors-game
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    accessControlAllowCredentials: true
    accessControlAllowMethods: [ "*" ]
    accessControlAllowOriginList: [ "*" ]
    accessControlAllowHeaders: [ "*" ]
    accessControlMaxAge: 100
    addVaryHeader: true
---

{{- $replicasMid := .Values.game.replicaCount | int -}}
{{- range $j := until $replicasMid }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-server-path-{{ $j }}
  namespace: {{ $.Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - "/server/{{ $j }}/"
---
{{- end }}
# Targets stateful sets of the game services
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: game-service
spec:
  entryPoints:
    - web
  routes:
    {{- $replicas := .Values.game.replicaCount | int -}}
    {{- range $i, $e := until $replicas }}
    - match: "PathPrefix(`/server/`) && Path(`/server/{{ $i }}/`)"
      kind: Rule
      services:
        - name: game-app-statefulset-{{ $i }}.game-svc.{{ $.Release.Namespace }}
          port: 8080
      middlewares:
        - name: cors-game
          namespace: {{ $.Release.Namespace }}
        - name: strip-server-path-{{ $i }}
          namespace: {{ $.Release.Namespace }}
    - match: "PathPrefix(`/server/`) && Path(`/server/{{ $i }}/ws`)"
      kind: Rule
      services:
        - name: game-app-statefulset-{{ $i }}.game-svc.{{ $.Release.Namespace }}
          namespace: {{ $.Release.Namespace }}
          port: 8080
      middlewares:
        - name: websocket-headers
          namespace: {{ $.Release.Namespace }}
        - name: cors-game
          namespace: {{ $.Release.Namespace }}
        - name: strip-server-path-{{ $i }}
          namespace: {{ $.Release.Namespace }}
    {{- end }}