{{- $replicas := .Values.game.replicaCount | int -}}
{{- $namespace := .Release.Namespace  }}
{{- range $i,$e := until $replicas }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    statefulset.kubernetes.io/pod-name: game-app-statefulset-{{ $i }}
  name: game-svc-{{ $i }}
  namespace: {{ $namespace  }}
spec:
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
    - protocol: TCP
      targetPort: 8081
      port: 8081
  selector:
    app: game-app
    statefulset.kubernetes.io/pod-name: game-app-statefulset-{{ $i }}
  type: LoadBalancer
{{- end }}