apiVersion: v1
kind: Service
metadata:
  labels:
    app: game-app
  name: game-svc-all-grpc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      name: internal-http-port
      targetPort: {{ .Values.env.INTERNAL_HTTP_PORT }}
      port:  80
  selector:
    app: game-app
  type: ClusterIP