apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: game-app
  name: game-app-statefulset
spec:
  replicas: {{ .Values.game.replicaCount }}
  serviceName: game-svc
  selector:
    matchLabels:
      app: game-app
  template:
    metadata:
      labels:
        app: game-app
    spec:
      containers:
        - image: {{ .Values.image.name}}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
              name: httpws
            - containerPort: 8081
              name: grpc
          imagePullPolicy: Always
          name: game-app
          resources:
            requests:
              memory: "20Mi"


