apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: game-app
  name: game-app-statefulset
spec:
  replicas: {{ .Values.game.replicaCount }}
  serviceName: game-svc
  selector:
    matchLabels:
      app: game-app
  template:
    metadata:
      labels:
        app: game-app
    spec:
      containers:
        - image: {{ .Values.image.name}}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.env.EXTERNAL_HTTP_PORT }}
              name: ext-http
            - containerPort:  {{ .Values.env.INTERNAL_HTTP_PORT }}
              name: int-http
          imagePullPolicy: Always
          name: game-app
          resources:
            requests:
              memory: "20Mi"
          env:
            - name: NATS_URL
              value: "{{ .Values.env.NATS_URL }}"
            - name: AUTH_EP
              value: "{{ .Values.env.AUTH_EP }}"
            - name: REQUIRE_AUTH
              value: "{{ .Values.env.REQUIRE_AUTH }}"
            - name: EXTERNAL_HTTP_PORT
              value: "{{ .Values.env.EXTERNAL_HTTP_PORT }}"
            - name: NUM_TEST_GAMES
              value: "{{ .Values.env.NUM_TEST_GAMES }}"
            - name: TEST_SERVER
              value: "{{ .Values.env.TEST_SERVER }}"
            - name: LOG_JSON
              value: "{{ .Values.env.LOG_JSON }}"
            - name: BACKUP_REDIS_URL
              value: "{{ .Values.env.BACKUP_REDIS_URL }}"
            - name: BOT_SERVICE_URL
              value: "{{ .Values.env.BOT_SERVICE_URL }}"
            - name: MIN_PLAYERS
              value: "{{ .Values.env.MIN_PLAYERS }}"
            - name: INTERNAL_HTTP_PORT
              value: "{{ .Values.env.INTERNAL_HTTP_PORT }}"
