apiVersion: v1
kind: Service
metadata:
  name: rso-game-svc
  namespace: apps
spec:
  selector:
    app: game-app
  ports:
    - protocol: TCP
      name: httpws
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: grpc
      port: 8081
      targetPort: 8081