apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: game-app
  name: game-app-statefulset
spec:
  replicas: {{ .Values.game.replicaCount }}
  serviceName: game-svc
  selector:
    matchLabels:
      app: game-app
  template:
    metadata:
      labels:
        app: game-app
    spec:
      containers:
        - image: {{ .Values.image.name}}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.env.EXTERNAL_HTTP_PORT }}
              name: ext-http
            - containerPort:  {{ .Values.env.INTERNAL_HTTP_PORT }}
              name: int-httpc
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          imagePullPolicy: Always
          name: game-app
          resources:
            requests:
              memory: "20Mi"
          env:
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
