apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-rso-cert
  namespace: traefik
spec:
  secretName: rso-cert
  dnsNames:
    - rso-2.{{ .Values.dns }}
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik
spec:
  defaultCertificate:
    secretName: rso-cert